# Imagen base con SDK de .NET para compilar el código
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copiar archivos del proyecto y restaurar dependencias
COPY *.csproj ./
RUN dotnet restore

# Copiar todo el código fuente y compilarlo
COPY . ./
RUN dotnet publish -c Release -o /app/publish

# Imagen base con runtime de .NET para ejecutar la app
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .

# Exponer el puerto donde corre la API
EXPOSE 8080
ENTRYPOINT ["dotnet", "AporopoApp_API.dll"]
