apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp-backend
  template:
    metadata:
      labels:
        app: todoapp-backend
    spec:
      containers:
        - name: backend
          image: jmjuangr/todoapp-backend:latest
          ports:
            - containerPort: 8080
