apiVersion: v1
kind: Service
metadata:
  name: todoapp-frontend-svc
  labels:
    app: todoapp-frontend
spec:
  type: LoadBalancer
  selector:
    app: todoapp-frontend
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-frontend-deploy
  labels:
    app: todoapp-frontend
spec:
  selector:
    matchLabels:
      app: todoapp-frontend
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todoapp-frontend
        tier: frontend
    spec:
      containers:
        - name: todoapp-frontend
          image: jmjuan/todoapp-frontend:latest
          ports:
            - containerPort: 80
